### ISSUE TITLE
Duplicates are not deleted when running the script multiple times (like in a crontab)

### ISSUE THREAD

**Issue by Arthur-Aillet** [Thezap/Linker_EPITECH_To_GOOGLE_Calendar#31]
I might be forgetting a flag or have misunderstand the usage  

I just use `python3 main.py`

(cool project tho)

![image](https://github.com/Thezap/Linker_EPITECH_To_GOOGLE_Calendar/assets/58011909/e4fdc6bc-e2c1-4425-84fe-fb564120be7e)
[calendar.log](https://github.com/Thezap/Linker_EPITECH_To_GOOGLE_Calendar/files/12855886/calendar.log)

**Comment by Thezap** [comment]
Thx 
I will look at it

Can you confirm to  me that there is `#codeevent=event-*` in the first line of the description in event on your calendar

**Comment by Thezap** [comment]
This bug was introduced by #30 
I will revert this line
https://github.com/Thezap/Linker_EPITECH_To_GOOGLE_Calendar/commit/08066d348f0801833d70821d5f8bae349bf693e4#diff-2e3cdbb2da536c76833d732b5233e21bd4e0112a90e135e4c10b47f706702949L73

**Comment by Thezap** [comment]
This should be fix by this commit https://github.com/Thezap/Linker_EPITECH_To_GOOGLE_Calendar/commit/3c922a5d1bb67ec194ef19f7196e458dbaf8dd60

I as not have future event in my calendar, I can't test this patch, feel free to reopen this issue if the problem was not fix.

(You may need to delete all event previously created manual as this doesn't delete already existing event (but should nor add event that already exist ))

**Comment by Arthur-Aillet** [comment]
I have re-setup the calendar with the new commits,

Everything work as expected now!

Thanks a lot for the reactivity :D
